
# springboot-secret.yaml: Store sensitive data (DB credentials)
apiVersion: v1
kind: Secret
metadata:
  name: springboot-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c3ByaW5n
  SPRING_DATASOURCE_PASSWORD: c3ByaW5nMTIz
