
# springboot-configmap.yaml: Store non-sensitive data (DB URL)
apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/mydatabase"
