# springboot-deployment.yaml: Deploy Spring Boot application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      # Ensure /app/logs exists and is writable before app starts
      initContainers:
        - name: init-logs-perms
          image: busybox:1.36
          command: ["sh","-c","mkdir -p /app/logs && chmod -R 777 /app/logs"]
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs

      containers:
        - name: springboot
          image: simpledotnet/devsecops-jenkins:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: springboot-config
            - secretRef:
                name: springboot-secret
          ports:
            - containerPort: 8089  # Match the port defined in Dockerfile
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs

      volumes:
        - name: app-logs
          emptyDir: {}
